// this file is autogenerated 
import AssignmentStatement from './AssignmentStatement';
import BinaryExpression from './BinaryExpression';
import CallExpression from './CallExpression';
import CallStatement from './CallStatement';
import Declaration from './Declaration';
import Expression from './Expression';
import FunctionDeclaration from './FunctionDeclaration';
import Identifier from './Identifier';
import IfExpression from './IfExpression';
import IfStatement from './IfStatement';
import LambdaExpression from './LambdaExpression';
import Literal from './Literal';
import LogicalExpression from './LogicalExpression';
import SourceCodeNode from './SourceCodeNode';
import Statement from './Statement';
import WhileStatement from './WhileStatement';

const blocks =  [
	AssignmentStatement,
	BinaryExpression,
	CallExpression,
	CallStatement,
	Declaration,
	Expression,
	FunctionDeclaration,
	Identifier,
	IfExpression,
	IfStatement,
	LambdaExpression,
	Literal,
	LogicalExpression,
	SourceCodeNode,
	Statement,
	WhileStatement,
];

export default blocks;
